/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author Andrey Salamanca
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form GestorPE
     */
    public Menu() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonRegistroEscuela = new javax.swing.JButton();
        ButtonRegistroCurso = new javax.swing.JButton();
        ButtonAsignarReCorrequisitos = new javax.swing.JButton();
        ButtonRegistroPlanesEstudio = new javax.swing.JButton();
        ButtonnConsultarPlanEstudio = new javax.swing.JButton();
        ButtonCosultasAdicionales = new javax.swing.JButton();
        ButtonModificarInfo = new javax.swing.JButton();
        ButtonGenerarEstadistica = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Gestor de Planes de Estudio");

        ButtonRegistroEscuela.setText("Registro de Escuela o Área Académica");
        ButtonRegistroEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistroEscuelaActionPerformed(evt);
            }
        });

        ButtonRegistroCurso.setText("Registro de Curso");
        ButtonRegistroCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistroCursoActionPerformed(evt);
            }
        });

        ButtonAsignarReCorrequisitos.setText(" Asignar requisitos y correquisitos a un curso");
        ButtonAsignarReCorrequisitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAsignarReCorrequisitosActionPerformed(evt);
            }
        });

        ButtonRegistroPlanesEstudio.setText("Registrar Planes de Estudio");
        ButtonRegistroPlanesEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistroPlanesEstudioActionPerformed(evt);
            }
        });

        ButtonnConsultarPlanEstudio.setText("Consular Plan de Estudio");
        ButtonnConsultarPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonnConsultarPlanEstudioActionPerformed(evt);
            }
        });

        ButtonCosultasAdicionales.setText("Consultas Adicionales");
        ButtonCosultasAdicionales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCosultasAdicionalesActionPerformed(evt);
            }
        });

        ButtonModificarInfo.setText("Modificar Informacion");
        ButtonModificarInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModificarInfoActionPerformed(evt);
            }
        });

        ButtonGenerarEstadistica.setText("Generar Estadisticas");
        ButtonGenerarEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGenerarEstadisticaActionPerformed(evt);
            }
        });

        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonAsignarReCorrequisitos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(ButtonRegistroEscuela))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(ButtonRegistroPlanesEstudio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(ButtonRegistroCurso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonGenerarEstadistica)
                    .addComponent(ButtonnConsultarPlanEstudio)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButtonCosultasAdicionales)
                        .addComponent(ButtonModificarInfo)))
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(ButtonSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegistroEscuela)
                    .addComponent(ButtonnConsultarPlanEstudio))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegistroCurso)
                    .addComponent(ButtonModificarInfo))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegistroPlanesEstudio)
                    .addComponent(ButtonCosultasAdicionales))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAsignarReCorrequisitos)
                    .addComponent(ButtonGenerarEstadistica))
                .addGap(18, 18, 18)
                .addComponent(ButtonSalir)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonRegistroEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistroEscuelaActionPerformed
        // Boton que va a la ventana Registrar escuela
        //new AddEscuela().setVisible(true);
        //this.setVisible(false);
        
    }//GEN-LAST:event_ButtonRegistroEscuelaActionPerformed

    private void ButtonModificarInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModificarInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonModificarInfoActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // Boton de salir
        //System.exit(0);
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void ButtonRegistroCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistroCursoActionPerformed
        // Boton que se dirige a la ventana Registrar Curso
        //new AddCurso().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_ButtonRegistroCursoActionPerformed

    private void ButtonRegistroPlanesEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistroPlanesEstudioActionPerformed
        // Boton que se va a la ventana Registro de Planes de estudio
        //new AddPlanEstudio().setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_ButtonRegistroPlanesEstudioActionPerformed

    private void ButtonAsignarReCorrequisitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAsignarReCorrequisitosActionPerformed
        // Boton que va a la ventana asingar requisitos y correquisitos a un curso
        // new AddRequisitoCorrequisito().setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_ButtonAsignarReCorrequisitosActionPerformed

    private void ButtonnConsultarPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonnConsultarPlanEstudioActionPerformed
        // Boton que va a la ventana consultar plan de estudio
        // new ConsultarPlanEstudio().setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_ButtonnConsultarPlanEstudioActionPerformed

    private void ButtonCosultasAdicionalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCosultasAdicionalesActionPerformed
        // TODO add your handling code here:
        // new ConsultasAdicionales().setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_ButtonCosultasAdicionalesActionPerformed

    private void ButtonGenerarEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGenerarEstadisticaActionPerformed
        // TODO add your handling code here:
        // new GenerarEstadisticas().setVisible(true);
        // this.setVisible(false);
    }//GEN-LAST:event_ButtonGenerarEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public  javax.swing.JButton ButtonAsignarReCorrequisitos;
    public javax.swing.JButton ButtonCosultasAdicionales;
    public javax.swing.JButton ButtonGenerarEstadistica;
    public javax.swing.JButton ButtonModificarInfo;
    public javax.swing.JButton ButtonRegistroCurso;
    public javax.swing.JButton ButtonRegistroEscuela;
    public javax.swing.JButton ButtonRegistroPlanesEstudio;
    public javax.swing.JButton ButtonSalir;
    public javax.swing.JButton ButtonnConsultarPlanEstudio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
